require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
flipperkit_version = '0.111.0'

target 'Auth0Samples' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  target 'Auth0SamplesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.9'})
  use_flipper!({ 'Flipper' => flipperkit_version, 'Flipper-Folly' => '2.6.9', 'Flipper-RSocket' => '1.4.3', 'Flipper-DoubleConversion' => '3.1.7', 'Flipper-Glog' => '0.3.9', 'Flipper-PeerTalk' => '0.0.4' })


  post_install do |installer|
  # Run the React-Native post install
  react_native_post_install(installer)

  # Reconfigure the pods to match the iOS version we're targetting
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      case target.name
        when 'RCT-Folly'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        else
          config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
        end
      end
    end
  end
end